import Testing

@testable import SplitBar
import Foundation

private func entry(
    id: String = UUID().uuidString,
    age: TimeInterval,
    text: String
) -> ClipboardEntry {
    ClipboardEntry(
        id: UUID(uuidString: id) ?? UUID(),
        timestamp: Date(timeIntervalSinceNow: -age),
        sourceBundleIdentifier: "com.example.app",
        isPinned: false,
        searchableText: text,
        payload: .text(text)
    )
}

struct ClipboardHardeningTests {
    @Test func concealedTransientAndAutoGeneratedAreSkipped() {
        #expect(ClipboardPrivacyFilter.shouldSkip(typeIdentifiers: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]))
        #expect(ClipboardPrivacyFilter.shouldSkip(typeIdentifiers: ["org.nspasteboard.TransientType"]))
        #expect(ClipboardPrivacyFilter.shouldSkip(typeIdentifiers: ["org.nspasteboard.AutoGeneratedType"]))
    }

    @Test func ordinaryContentIsCaptured() {
        #expect(!ClipboardPrivacyFilter.shouldSkip(typeIdentifiers: ["public.utf8-plain-text", "public.url"]))
        #expect(!ClipboardPrivacyFilter.shouldSkip(typeIdentifiers: []))
    }

    @Test func defaultExclusionsCoverPasswordManagers() {
        let defaults = ClipboardPrivacyFilter.defaultExcludedBundleIdentifiers
        for bundle in [
            "com.1password.1password",
            "com.agilebits.onepassword7",
            "com.bitwarden.desktop",
            "com.dashlane.dashlanephonefinal",
            "org.keepassxc.keepassxc",
            "com.apple.Passwords",
            "com.apple.keychainaccess",
        ] {
            #expect(defaults.contains(bundle))
        }
        // A normal app must not be excluded.
        #expect(!defaults.contains("com.apple.Safari"))
    }

    @Test func excludedBundleIsNotCaptured() {
        #expect(!shouldCaptureClipboard(
            frontmostBundleIdentifier: "com.1password.1password",
            excludedBundleIdentifiers: ClipboardPrivacyFilter.defaultExcludedBundleIdentifiers
        ))
        #expect(shouldCaptureClipboard(
            frontmostBundleIdentifier: "com.apple.Safari",
            excludedBundleIdentifiers: ClipboardPrivacyFilter.defaultExcludedBundleIdentifiers
        ))
    }

    @Test func oneDayWindowDropsOlderEntries() {
        let policy = ClipboardRetentionPolicy(maxEntries: 100, maxBlobBytes: 1024, window: .oneDay)
        let now = Date()
        let history = [
            entry(age: 60, text: "fresh"),
            entry(age: 3_600, text: "hour-old"),
            entry(age: 90_000, text: "stale"),
        ]
        let kept = policy.prune(history, now: now)
        #expect(kept.count == 2)
        #expect(kept.allSatisfy { $0.searchableText != "stale" })
    }

    @Test func oneHourAndOneHourAreRespected() {
        let oneHour = ClipboardRetentionPolicy(maxEntries: 10, maxBlobBytes: 10, window: .oneHour)
        let kept = oneHour.prune([entry(age: 30, text: "new"), entry(age: 7_200, text: "old")], now: Date())
        #expect(kept.count == 1)
        #expect(kept.first?.searchableText == "new")
    }

    @Test func untilClearedKeepsEverything() {
        let policy = ClipboardRetentionPolicy(maxEntries: 100, maxBlobBytes: 1024, window: .untilCleared)
        let kept = policy.prune([entry(age: 999_999, text: "ancient")], now: Date())
        #expect(kept.count == 1)
    }

    @Test func mergeStillAppliesCountLimitAndExpiry() {
        let policy = ClipboardRetentionPolicy(maxEntries: 3, maxBlobBytes: 1024, window: .oneDay)
        let history = [entry(age: 10, text: "a"), entry(age: 100_000, text: "expired")]
        let merged = mergeClipboardEntry(
            history: history,
            candidate: entry(age: 0, text: "new"),
            policy: policy
        )
        #expect(merged.count == 2)
        #expect(merged.allSatisfy { $0.searchableText != "expired" })
    }

    @Test func duplicateCandidateIsIgnored() {
        let policy = ClipboardRetentionPolicy(maxEntries: 10, maxBlobBytes: 1024)
        let existing = entry(age: 5, text: "same")
        let merged = mergeClipboardEntry(history: [existing], candidate: existing, policy: policy)
        #expect(merged.count == 1)
    }

    @Test func historyFileIsOwnerOnly() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("clipboard-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: root) }
        let persistence = ClipboardPersistence(baseURL: root)
        try persistence.saveHistory([entry(age: 0, text: "secret")])
        let attributes = try FileManager.default.attributesOfItem(atPath: root.appendingPathComponent("clipboard_history.json").path)
        let mode = (attributes[.posixPermissions] as? NSNumber)?.int16Value ?? 0
        #expect(mode & 0o077 == 0, "history must not be group/other readable (mode was \(String(mode, radix: 8)))")
    }

    @Test func blobFilesAreOwnerOnly() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("clipboard-blob-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: root) }
        let persistence = ClipboardPersistence(baseURL: root)
        try persistence.saveBlob(data: Data([1, 2, 3]), relativePath: "image.png")
        let url = root.appendingPathComponent("blobs/image.png")
        let attributes = try FileManager.default.attributesOfItem(atPath: url.path)
        let mode = (attributes[.posixPermissions] as? NSNumber)?.int16Value ?? 0
        #expect(mode & 0o077 == 0, "blob must not be group/other readable (mode was \(String(mode, radix: 8)))")
    }
}
