import AppKit
import Foundation

/// How long clipboard history is kept. Count and byte limits still apply on top
/// of this; whichever bound trips first wins.
public enum ClipboardRetentionWindow: String, Codable, CaseIterable, Identifiable, Sendable {
    case oneHour
    case oneDay
    case oneWeek
    case untilCleared

    public var id: String { rawValue }

    public var title: String {
        switch self {
        case .oneHour: "1 hour"
        case .oneDay: "24 hours"
        case .oneWeek: "7 days"
        case .untilCleared: "Until cleared"
        }
    }

    public var seconds: TimeInterval? {
        switch self {
        case .oneHour: 3600
        case .oneDay: 86_400
        case .oneWeek: 604_800
        case .untilCleared: nil
        }
    }
}

public struct ClipboardRetentionPolicy: Codable, Equatable, Sendable {
    public let maxEntries: Int
    public let maxBlobBytes: Int
    /// New field; absent in older configurations, which keeps history until
    /// cleared, matching the previous behaviour.
    public let window: ClipboardRetentionWindow

    public init(
        maxEntries: Int,
        maxBlobBytes: Int,
        window: ClipboardRetentionWindow = .untilCleared
    ) {
        self.maxEntries = maxEntries
        self.maxBlobBytes = maxBlobBytes
        self.window = window
    }

    /// Drops entries older than the window. Entries with no timestamp are kept.
    public func prune(_ entries: [ClipboardEntry], now: Date) -> [ClipboardEntry] {
        guard let seconds = window.seconds else { return entries }
        let cutoff = now.addingTimeInterval(-seconds)
        return entries.filter { entry in
            guard entry.timestamp > .distantPast else { return true }
            return entry.timestamp >= cutoff
        }
    }
}

/// Pasteboards that announce themselves as private must never be captured.
///
/// macOS defines these marker types: apps (notably password managers) set
/// `ConcealedType` for "this is a secret, do not persist", `TransientType` for
/// "do not even offer it elsewhere", and `AutoGeneratedType` for machine-only
/// values.
public enum ClipboardPrivacyFilter {
    public static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    public static let blockedTypes: Set<String> = [
        concealedType.rawValue,
        transientType.rawValue,
        autoGeneratedType.rawValue,
    ]

    /// Pure so it can be unit tested without a pasteboard.
    public static func shouldSkip(typeIdentifiers: [String]) -> Bool {
        typeIdentifiers.contains { blockedTypes.contains($0) }
    }

    /// Bundle identifiers excluded by default: password managers and password
    /// vaults must never feed clipboard history.
    public static let defaultExcludedBundleIdentifiers: Set<String> = [
        "com.1password.1password",
        "com.1password.1password-browser",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
    ]
}
